### ISSUE TITLE
[BUG] : React Toastify does not work properly 

### ISSUE THREAD

**Issue by Kl0099** [priyanshpatel12345/MERN-_Thapa#2]
https://github.com/priyanshpatel12345/MERN-_Thapa/assets/144949883/9240d4e1-59d1-4a46-b3e2-2cef49ec8cd5

Whenever you log out, a message should be displayed saying 'Logged out successfully.'

**Comment by priyanshpatel12345** [comment]
I fixed the issue present in "MERN-_Thapa repository".
